import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import {
  PrismaClient,
  UserRole,
  RoomType,
  AccessType,
} from '../src/generated/prisma/client';
import * as bcrypt from 'bcrypt';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const ZONE_ROOMS = [
  {
    key: 'VITE_ROOM_MEETING_A_ID',
    name: 'Meeting Room A',
    type: RoomType.MEETING,
    capacity: 10,
  },
  {
    key: 'VITE_ROOM_MEETING_B_ID',
    name: 'Meeting Room B',
    type: RoomType.MEETING,
    capacity: 10,
  },
  {
    key: 'VITE_ROOM_LECTURE_ID',
    name: 'Lecture Hall',
    type: RoomType.MEETING,
    capacity: 30,
  },
  {
    key: 'VITE_ROOM_LIBRARY_ID',
    name: 'Library',
    type: RoomType.FOCUS,
    capacity: 20,
  },
  {
    key: 'VITE_ROOM_CHILLING_ID',
    name: 'Chill Zone',
    type: RoomType.WORKSPACE,
    capacity: 20,
  },
  {
    key: 'VITE_ROOM_PRIVATE_ID',
    name: 'Private Room',
    type: RoomType.MEETING,
    capacity: 6,
  },
] as const;

async function main() {
  // ── Admin user ────────────────────────────────────────────────────────────
  const username = process.env.SEED_ADMIN_USERNAME ?? 'admin';
  const email = process.env.SEED_ADMIN_EMAIL ?? 'admin@metasphere.dev';
  const password = process.env.SEED_ADMIN_PASSWORD ?? 'Admin1234!';
  const firstName = process.env.SEED_ADMIN_FIRSTNAME ?? 'Super';
  const lastName = process.env.SEED_ADMIN_LASTNAME ?? 'Admin';

  const hashed = await bcrypt.hash(password, 10);

  const admin = await prisma.user.upsert({
    where: { username },
    create: {
      username,
      email,
      password: hashed,
      firstName,
      lastName,
      role: UserRole.ADMIN,
    },
    update: { email, password: hashed, role: UserRole.ADMIN },
  });

  console.log(`\n✔  Admin  id=${admin.id}  username=${admin.username}`);

  // ── Zone rooms ────────────────────────────────────────────────────────────
  console.log('\n── Zone rooms ──');

  const envLines: string[] = [];

  for (const room of ZONE_ROOMS) {
    const existing = await prisma.room.findFirst({
      where: { name: room.name },
    });

    const record = existing
      ? await prisma.room.update({
          where: { id: existing.id },
          data: { type: room.type, capacity: room.capacity, isActive: true },
        })
      : await prisma.room.create({
          data: {
            name: room.name,
            type: room.type,
            capacity: room.capacity,
            accessType: AccessType.PUBLIC,
            isActive: true,
            createdById: admin.id,
          },
        });

    console.log(
      `  ${existing ? 'updated' : 'created'}  ${room.key}=${record.id}  (${room.name})`,
    );
    envLines.push(`${room.key}=${record.id}`);
  }

  // ── Write .env.local for the frontend ─────────────────────────────────────
  const fs = await import('fs');
  const path = await import('path');

  const envPath = path.resolve(process.cwd(), '.env.seed-output');
  const content = [
    '# Generated by prisma/seed.ts — copy these into meta-sphere-web/.env.local',
    ...envLines,
    '',
  ].join('\n');

  fs.writeFileSync(envPath, content, 'utf8');
  console.log(`\n✔  Room env vars written to: ${envPath}`);
  console.log('    Copy the lines above into meta-sphere-web/.env.local\n');
}

main()
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
